version: '3.9'
services:
  postgres:
    image: postgres:14
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: redis-container
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: chat-server
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
    # Переменные окружения для подключения к сервисам
    # Если вы хотите передать их внутрь приложения:
     - POSTGRES_DSN=postgres://user:password@postgres:5432/postgres?sslmode=disable
     - REDIS_ADDR=redis:6379
     - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    ports:
      - "50051:50051"
